### PR TITLE
RFC of WIP: Cargo adjustments

### PR DESCRIPTION
**Pull request by Byron**
This PR will not merge and represents my ongoing work to make file-lock suitable for cargo. This involves primarily the API.

Please let me know what you think so that I can make the desired changes and/or incorporate your input into future work.

Cheers and Thanks

### CODE REVIEW

**Comment by alfiedotwtf** [comment]
Wow! Mighty effort. I'll go through them today.

**Comment by Byron** [comment]
Thank you ! It's already working to some extend - the cargo modifications are done [in this PR](https://github.com/rust-lang/cargo/pull/1764).

**Comment by alfiedotwtf** [comment]
Looking at it again, I think we can ignore it. The fcntl() call requires a flock struct, which has nothing to do with flock(), so there's precident :)

Ok, I'll roll back my changes so I can merge yours. There's a bit of cleanup todo (nothing major), but I'll leave them for now while you are still in flux. When you're happy for it to be stable for a while, I'll go through and clean it up.

**Comment by alfiedotwtf** [comment]
Awesome, thanks for the hard work!

**Comment by alfiedotwtf** [comment]
Just staring at the documentation, and maybe I think that the flock module may add a bit of confusion. What do you thing about renaming the lock and flock modules to:

* file_lock::by_fd
* file_lock::by_filename

That way, it's obvious that there are two ways on interacting with the crate - by filedescriptor and by filename.

Thoughts?

**Comment by Byron** [comment]
I like it, and might even suggest to remove the `by_` to get shorter names. This also might imply that we don't import anything anymore into the crate top-level, and that we can possibly rename the `FileLock`structure to be just `Lock`.

If in doubt, I will go with the `by_` prefixes though.

What do you say ?

**Comment by alfiedotwtf** [comment]
You're right. Having the shorter names is still meaningful and shouldn't confuse. Awesome, no by_ prefix :)

**Comment by alfiedotwtf** [comment]
> possibly rename the FileLockstructure to be just Lock

Sounds good :)

**Comment by Byron** [comment]
Ok, I will make the changes accordingly. 

The good thing is that everything can be changed once there seems to be an even better solution, so experiments are totally risk free.

**Pull request merged**
