### PR TITLE
RFC of WIP: API adjustments

### PR DESCRIPTION
**Pull request by Byron**
This PR contains an experiment steered towards an API which should be most usable by Cargo. The major changes are:

* decouple file-creation from file-locking
* object-oriented interface for `Lock`
* more options for the actual lock to allow shared read-locks as well. This is done to be explicit about the kind of lock one acquires.

Additionally a multi-process test-case was added to verify the lock actually does as one would expect.

# Open Questions

For some reason, even the multi-process test cannot verify the locking actually works, and I wonder what the problem could be.

### CODE REVIEW

**Comment by Byron** [comment]
Here is the [failing inter-process test](https://travis-ci.org/alfiedotwtf/file-lock/jobs/68184367#L169). I'd be super happy to pick your brain on why this doesn't work.

**Comment by Byron** [comment]
Ah, the test was fixed now and proves it actually works. Next is to try to make good use of the functionality in cargo.

**Comment by alfiedotwtf** [comment]
Wow, big changes. Slowly going through them... sorry.

As for the original reason of the sporadic failing of tests, I remember now that it was definitely because Cargo was running tests in parallel. Whon forcing to a single thread, I couldn't reproduce it failing.

**Comment by alfiedotwtf** [comment]
Thanks for the great work!

**Comment by Byron** [comment]
Thanks for merging ! 
I will be testing it with cargo, and add some `clog` configuration to allow to easily create changelogs, possibly in preparation for an upcoming release on crates.io.

**Comment by alfiedotwtf** [comment]
No problem. I'll try to keep up with you and review as soon as you push :)

**Pull request merged**
