### PR TITLE
Cargo adjustments Part II

### PR DESCRIPTION
**Pull request by Byron**
This PR contains the changes discussed in the [previous incarnation](https://github.com/alfiedotwtf/file-lock/pull/6) of the very same topic.

### CODE REVIEW

**Comment by Byron** [comment]
A [new cargo PR](https://github.com/rust-lang/cargo/pull/1781) was created to work on making cargo multi-process safe.

Once it was approved generally, I will work on implementing the file-lock mechanism for windows.

**Comment by alfiedotwtf** [comment]
Once again, thanks for your great work!

**Comment by Byron** [comment]
Welcome, even though I am not sure if it is that great at all. Maybe time will tell.

**Comment by alfiedotwtf** [comment]
What are you not happy about? I'm thinking it's interface is looking good now.

**Comment by Byron** [comment]
Right now it seems to be used and steered just by cargo, which could cause the API to be too narrow as it has only one focus point.
I think it already does its job sufficiently well, and maybe I am just not trusting my code in general until there are multiple uses of it serving as proof it actually works as intended.

Something I am unsure about is the enforced call to `unlock` in the destructors, even though `lock` might not have been called yet. A unit-test shows that this is not a problem, yet it's the question whether the system call should be prevented by keeping this kind of state in the struct. It could be an improvement I make next time.

**Comment by alfiedotwtf** [comment]
Ah. The problem with destructors is what to do in case of a failure? You can't really recover if drop() is called when a binding goes out of scope. However, within the unlock() itself, we could check if a lock already exists before continuing with the unlock. When I get a bit of time I'll have a look (possibly after your Windows changes have landed).

**Pull request merged**
